### ISSUE TITLE
Recently played matches should appear on main page

### ISSUE THREAD

**Issue by ybbun** [AdmiralGT/ttennis_ladder#1]
So people know their opponent has entered a match.

Ideally put rankings on the left, recently played matches in the middle, inactive players on the right.

**Comment by AdmiralGT** [comment]
I've got the javascript working to print out the recent results. Need to update the HTML to actually display it nicely but that shouldn't be too difficult...

**Comment by AdmiralGT** [comment]
I've updated the HTML and CSS. Might look a bit funky still but that shouldn't be too difficult to resolve.
