### ISSUE TITLE
Make each player's recent results look nicer

### ISSUE THREAD

**Issue by ybbun** [AdmiralGT/ttennis_ladder#12]
Would be nice to distinguish the wins and losses more easily and make it clear what a player's progress is. So for example, at
http://saturday:90/player.html?GRT
- Have GRT on the left each time, then change "beat" to "lost to" where necessary
- Show the (-6) in red on the left for losses, and the (+28) on the left in green for wins.
This looks neater because you can just scan the left half for that player's info and +/- points, rather than having to look left and right.

**Comment by AdmiralGT** [comment]
I've updated the template to always display the player in question on the left and the opponent on the right.
