### ISSUE TITLE
Add 3rd column to main page with cool random other stuff

### ISSUE THREAD

**Issue by ybbun** [AdmiralGT/ttennis_ladder#14]
I think we want:
- Main rankings in the middle
- Recent results on the right
- Cool other stuff on the left
- Greyed out inactive players down below.
  Check it's possible to have 3 columns with sensible resolutions without wrapping.

The "other stuff" could include:
- Biggest upsets of the last month
- Expected win % for differences in rating (100 = 64%, 200 = 76% etc)
- News ("Table out of action this week")
- Latest updates Geoff has made to the site

**Comment by derek-cheong** [comment]
Nice.  Suggest giving the left and right "columns" a bit of top padding/margin, so the main results section is a bit more prominent.

**Comment by ybbun** [comment]
Yep. Maybe bigger font for the main rankings. Also try to make the other columns about the same height as the middle column (i.e. include more recent results), add a sensible amount of other stuff.

**Comment by derek-cheong** [comment]
I've prototyped this (branch issue14) by adding a placeholder left column.  Do we have any useful content to go in there?

**Comment by AdmiralGT** [comment]
At the moment know, we could have a biggest upset in most recent X games?

**Comment by ybbun** [comment]
One thing to check is that having 3 columns doesn't cause wrapping or otherwise bad formatting on lower resolutions.

Also I think it's worth adding the text below in the left column even if there's no other content for it yet. Having the extra column moves the actual rankings to the middle where they are more prominent. 

Points difference: Expected win %
100: 64%
200: 76%
300: 85%
400: 91%
500: 95%
600: 97%

**Comment by derek-cheong** [comment]
I think the only way to avoid wrapping/bad formatting is to have a container div with a fixed width.  Means that lower resolution screens will have a horiz scroll bar, but I'm OK with that.  (this doesn't apply to phones, which we'll need to do a complete restyle for).

**Comment by ybbun** [comment]
I think we've got enough content for the left column already:
- Expected win %s (above)
- Link to the github repo
- Mention that the balls will be kept topped up by ATN because I've bought some with a table tennis budget
- How to book the table

**Comment by derek-cheong** [comment]
Left column feels a bit narrow for some of this content.  Expected win percentage probably just about fits, but not sure about the rest.

Suggest adding a separate "about page" instead, then it might also make sense to have a permanent nav bar with "home" and "about" links.

**Comment by derek-cheong** [comment]
I've put all the extra info on the new "about" page, so now it's just the expected win %age in the left hand column, which is a bit too sparse.  Suggest we hold off on the three columns until we have more dynamically generated content to put into the left hand column, e.g. biggest shocks of the month.

**Comment by derek-cheong** [comment]
The main column is a little wider, after update to win/loss entries.  This means that if we do add a third column it'll be even narrower than it was previously.  Suggest we just stick with two columns.  If/when we ever add cool new features, they can go in the secondary column (e.g. under the current recent results table).  Comment/ reopen this if you disagree.
