### ISSUE TITLE
Need some way to refresh the ladder after manually editing the database.

### ISSUE THREAD

**Issue by AdmiralGT** [AdmiralGT/ttennis_ladder#17]
Currently if the database is manually changed you have to stop/start the server to pick up the changes. We should have some sort of manual refresh in order to be able to fix this.

**Comment by derek-cheong** [comment]
Really?  How often are you expecting to need to do this?  How difficult is it currently to to stop/start the server?

If you do this, are you going to make this available to site admins only?  Do we even have the concept of admins right now?  At the very least, we should make this a hidden option.

**Comment by AdmiralGT** [comment]
My intention is to have a script similar to the ./start to kick it off. Stopping the server basically entails killing the python process which can result in killing the other ladders hosted on the server (because there's no way to identify which server the resting.py is running).

Also a script will improve our uptime, I think a target of 5 9s uptime is fair for the ladder.

**Comment by derek-cheong** [comment]
But the issue says "reload button"...

**Comment by AdmiralGT** [comment]
This has actually been resolved as part of https://github.com/AdmiralGT/ttennis_ladder/pull/51 when fixing issue #47 so closing.
