### ISSUE TITLE
Players with fewer than 10 games have a misaligned "Past"

### ISSUE THREAD

**Issue by AdmiralGT** [AdmiralGT/ttennis_ladder#27]
Taking PGC as an example, the L's are misaligned compared to players with a complete set of 10 results.

**Comment by derek-cheong** [comment]
I think we should completely rework this column.  At the moment the alignment is relying on fixed width font being right aligned.  If we ever want o switch to a non-fixed width font, this isn't going to work.  Suggest we have individual div elements with fixed widths, or something. 

Arguably a separate issue, but it's not worth fixing weird alignment if we're going to rework the layout.

**Comment by derek-cheong** [comment]
Unless it's really easy, which it probably is.

**Comment by derek-cheong** [comment]
I've made the quick fix.  Leaving this open to consider fixing properly.  Maybe we can even replace w/l with win/loss icons.  Changing this to an enhancement.
