### ISSUE TITLE
Reduce overall height of title and picture

### ISSUE THREAD

**Issue by AdmiralGT** [AdmiralGT/ttennis_ladder#33]
There's quite a lot of space used by the Nav Bar, Title and Picture meaning more scrolling (especially for those lowers on the ladder!). Since the Nav Bar is pretty sparse, we should reduce the width to allow the title to be moved up.

Additionally, a small reduction in size of the picture might also save us some height.

**Comment by derek-cheong** [comment]
Moving the title inline with the navbar presents the problem that the title is no longer centred.  I don't really want to hack this by adding an equally wide empty spacer on the other side.  I'll have a think about the layout.  Might make more sense to float the title left and move the navbar to the right or something similar.

**Comment by derek-cheong** [comment]
@AdmiralGT not keen on reformat, so we just made the doodle smaller and reduced default padding on the h1 tag.
