### ISSUE TITLE
Include points difference or percent chance between players in biggest upsets list

### ISSUE THREAD

**Issue by ybbun** [AdmiralGT/ttennis_ladder#38]
e.g. if 1401 beats 1606, add 205, and/or 22% on the right, to show the points difference overcome, and/or chance of achieving it.

**Comment by AdmiralGT** [comment]
This is done now isn't it?

**Comment by ybbun** [comment]
no

**Comment by AdmiralGT** [comment]
I've created a pull request with this change, not quite happy with the styling so feedback welcome.
https://github.com/AdmiralGT/ttennis_ladder/pull/44

**Comment by AdmiralGT** [comment]
Merged pull request, done.
