### ISSUE TITLE
Change biggest upsets to biggest recent updates?

### ISSUE THREAD

**Issue by derek-cheong** [AdmiralGT/ttennis_ladder#40]
Biggest updates table is currently dominated by AWI vs ATN.  As hilarious as this is, it's not as inclusive as it could be...

Until we have timestamps in the database, we could maybe limit this to the biggest upsets in the last N results (where N is say 50).  

Thoughts?

**Comment by AdmiralGT** [comment]
Sounds good, I'll do that at the weekend

**Comment by AdmiralGT** [comment]
Fixed in commit ca26aff. Currently set to 100 most recent games.
