### ISSUE TITLE
Add 3-way results entry

### ISSUE THREAD

**Issue by andrew-nubbert** [AdmiralGT/ttennis_ladder#48]
Very often (perhaps twice a week) there are 3 people at the table and they play singles games alternately like this:
A plays B
A plays C
B plays C
[repeat many times]

Entering these results in chronological order is annoying because you have to keep changing the initials. So it would be great if there was an alternative option to enter results where 3 initials could be entered, and buttons pressed for results between any two.

Perhaps have a link from the main page "3-way results entry" offering 3 text boxes for the names and 6 buttons for the possible results.

**Comment by AdmiralGT** [comment]
I've implemented this and merged to master. Here's a screenshot of what it looks like. I'll update saturday on Monday with this function. Let me know if you have any feedback.

https://imgur.com/dYpqGfG
