### ISSUE TITLE
Improve UI for adding games

### ISSUE THREAD

**Issue by ybbun** [AdmiralGT/ttennis_ladder#6]
It's annoying entering the same set of initials repeatedly and clicking Add each time. Many options for fixing, but imo this is the best:

1. Change the "add" button to two buttons, one for each player, for if that person won a game.
2. Put the most recently played games on the front page (that's tracked by another issue)
3. Leave the initials in place after entering a result, rather than deleting them from their text boxes.

- Given that 3 happens, you now use 2 to know that it worked when you clicked the winner button for one of the players.
- Use a combo of 1 and 3 to enter lots of results fast.

Sorted.

Other options:
- Have "x2", "x3" buttons etc for adding multiple games at once.
- Add a timestamped message showing "result added at <time>" so you know the Add worked.

**Comment by AdmiralGT** [comment]
I've added the option 1 style as a separate input. Not sure whether to get rid of the existing add button and input function, we can discuss when you're back in on Tuesday.

**Comment by AdmiralGT** [comment]
Fix is committed and in use.
